
name: luway
description: LuWay - Global car search and marketplace application
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  
  # Authentication
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^6.1.1
  
  # UI & Responsive
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  
  # Images & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  image: ^4.1.7
  
  # Storage & Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Network & Connectivity
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  http: ^1.1.0
  
  # Location
  geolocator: ^10.1.0
  
  # Permissions & Utils
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^17.0.0
  
  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Payments
  in_app_purchase: ^3.1.11
  
  # Country & Location
  country_picker: ^2.0.21
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo.png
    - assets/google_logo.png
    - assets/animations/
    - assets/sound/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
          weight: 300
