services:
  - type: web
    name: luway-notification-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production