// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_IEUJ6T2c0Uz-b25fOOdrDOr4-R53VJE',
    appId: '1:1051617182942:web:YOUR_WEB_APP_ID',
    messagingSenderId: '1051617182942',
    projectId: 'bipcar-7464a',
    authDomain: 'bipcar-7464a.firebaseapp.com',
    databaseURL: 'https://bipcar-7464a-default-rtdb.firebaseio.com',
    storageBucket: 'bipcar-7464a.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IEUJ6T2c0Uz-b25fOOdrDOr4-R53VJE',
    appId: '1:1051617182942:android:1a47d916183301cd18ee4f',
    messagingSenderId: '1051617182942',
    projectId: 'bipcar-7464a',
    databaseURL: 'https://bipcar-7464a-default-rtdb.firebaseio.com',
    storageBucket: 'bipcar-7464a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IEUJ6T2c0Uz-b25fOOdrDOr4-R53VJE',
    appId: '1:1051617182942:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '1051617182942',
    projectId: 'bipcar-7464a',
    authDomain: 'bipcar-7464a.firebaseapp.com',
    databaseURL: 'https://bipcar-7464a-default-rtdb.firebaseio.com',
    storageBucket: 'bipcar-7464a.firebasestorage.app',
    iosBundleId: 'com.studio085.luway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_IEUJ6T2c0Uz-b25fOOdrDOr4-R53VJE',
    appId: '1:1051617182942:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '1051617182942',
    projectId: 'bipcar-7464a',
    authDomain: 'bipcar-7464a.firebaseapp.com',
    databaseURL: 'https://bipcar-7464a-default-rtdb.firebaseio.com',
    storageBucket: 'bipcar-7464a.firebasestorage.app',
    iosBundleId: 'com.studio085.luway',
  );
}
